using Microsoft.AspNetCore.Mvc;
using _20051350008.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using _20051350008.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Components.Forms;

namespace _20051350008.Controllers
{
    public class DepartmentController : Controller
    {

        private readonly DepartmentContext _context;

        public DepartmentController(DepartmentContext context)
        {
            this._context = context;
        }

        public async Task<List<DepartmentModel>> GetListAsync()
        {
            var departments = await _context.Department.ToListAsync();
            return departments;
        }

        public async Task OnGetAsync()
        {
            //var employees = await _context.Employee.ToListAsync();
        }
        public ActionResult Index()
        {

            ViewBag.Message = "Department Example";
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
        public ActionResult List()
        {
            var Departments = _context.Department.ToList();
            return View(Departments);
        }

        private DepartmentModel Get(int Id1)
        {
            List<DepartmentModel> Department = _context.Department.ToList();
            foreach (DepartmentModel dept in Department)
            {
                //Console.WriteLine(employee);
                if (dept.Id == Id1)
                {
                    return dept;
                }
            }
            return null;
        }
        public ActionResult Edit(int Id)
        {
            var dept = this.Get(Id);
            return View(dept);
        }

        public ActionResult New()
        {

            return View("Edit");
        }

        public ActionResult Update(int Id, DepartmentModel deptForm)
        {
            var dept = this.Get(Id);

            if (dept == null)
            {

                DepartmentModel dept1 = new(

                     0, // Set Id if it's not autogenerated, otherwise remove this line
                     deptForm.DepartmentName,
                     deptForm.ManagerName
                );

                _context.Department.Add(dept1); // Assuming _context is your DbContext


            }
            else
            {

                //dept.Id = Id;
                dept.DepartmentName = deptForm.DepartmentName;
                dept.ManagerName = deptForm.ManagerName;

            }
            _context.SaveChanges();

            return View("Edit", dept);
        }

    }
}
